/**
 * The set of environment variables available client-side.
 * These are not from the runtime environment, but hardcoded at build-time from the build environment (or `.env` file)
 * into the client code.
 *
 * THE VALUES OF THESE VARIABLES SHOULD NOT CONTAIN ANY SECRETS!
 */
export const PUBLIC_ENV_VARS = [
  'AI_ASSISTANT_REMOTE_ENTRY_MODULE',
  'AI_ASSISTANT_REMOTE_ENTRY_URL',
  'AI_SKILLS_REMOTE_ENTRY_MODULE',
  'AI_SKILLS_REMOTE_ENTRY_URL',
  'APP_DOMAIN',
  'BASENAME_URL_SEGMENT',
  'AUTH_TOKEN',
  'FILE_MANAGEMENT_REMOTE_ENTRY_MODULE',
  'FILE_MANAGEMENT_REMOTE_ENTRY_URL',
  'MATTERS_REMOTE_ENTRY_MODULE',
  'MATTERS_REMOTE_ENTRY_URL',
  'ONEPASS_SIGNON_URL',
  'ONETRUST_DOMAIN_ID',
  'PLATFORM_ENV',
  'PUBLIC_URL',
  'SUPPRESS_LOGGING',
  'TR_KORE_SUPPORT_CHATBOT_ENVIRONMENT',
  'TR_KORE_SUPPORT_CHATBOT_URL',
  'TR_PENDO_APPLICATION_ID',
  'WIJMO_LICENSE_KEY',
  'ONESOURCE_PLATFORM_URL',
];
